### ISSUE TITLE
Issue-Readme improvements and explanations

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#101]
Automated Review Comments
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
