### ISSUE TITLE
Issue-Ponemos 7 decimalesi

Los mismos que las estrellas de la bandera de la comunidad

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#103]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
