### ISSUE TITLE
Issue-Develop - Crear blockchain de test para desarrollar DAPPs.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#113]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
Issues in scripts/deploy.py:
  - (11, 'Missing docstring for function')
  - (30, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
