### ISSUE TITLE
Issue-Actualizado airdrop:

- Guardamos la cantidad que se asigna a cada direccion.
- Se emite un mensaje cuando se ha asignan tokens (para web3 por ejemplo)
- Constructor de airdrop

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#17]
Automated Review Comments
Issues in contracts/Airdrop.sol:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
