### ISSUE TITLE
Issue-Add: testing con brownie (eth-brownie)

Usamos un entorno de desarrollo y test basado en Python
y no en nodeJS (como suele ser habitual).

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#31]
Automated Review Comments
Issues in tests/test_ayusocoin.py:
  - (8, 'Missing docstring for function')
  - (11, 'Missing docstring for function')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
