### ISSUE TITLE
Issue-Test ERC20 transferFrom() con permiso ilimitado

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#41]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (3, 'Line exceeds 80 characters')
  - (13, 'TODO found')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in tests/test_ayusocoin.py:
  - (3, 'Missing docstring for function')
  - (6, 'Line exceeds 80 characters')
  - (23, 'Missing docstring for function')

**Comment by kazupot7** [comment]
I got it.
