### ISSUE TITLE
Issue-Airdrop tests

- Solo se puede hacer claim una vez
- Token modificado para usar transfer() desde contrato
- Airdorp modificado: usa index en vez de msg.sender para hacer claim en nombre de otros

Airdrop tests

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#43]
Automated Review Comments
Issues in contracts/Airdrop.sol:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in contracts/Ayusocoin.sol:
  - (9, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
Issues in tests/test_airdrop.py:
  - (14, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
