### ISSUE TITLE
Issue-Add: _root address para gestionar contrato

Closes #6

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#55]
Automated Review Comments
Issues in contracts/Ayusocoin/Ayusocoin.sol:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in tests/test_ayusocoin.py:
  - (2, 'Missing docstring for function')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
