### ISSUE TITLE
Issue-Actualizadas fases y explicación

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#62]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
