### ISSUE TITLE
Issue-Utilizamos interfaz ERC20

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#72]
Automated Review Comments
Issues in contracts/Faucet.sol:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
