### ISSUE TITLE
Issue-Usamos test_proxy para comprobar cobertura y funcionamiento

Hay que probar el token cuando se llama desde otros contratos.
Por ejemplo, uniswap o similares necesitan esta funcionalidad.
Se ha probado antes en directo pero no desde un contrato
de solidity antes.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/Ayusocoin#78]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (9, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
Issues in tests/test_ayusocoin.py:
  - (4, 'Missing docstring for function')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
